name             'main'
maintainer       'Pulvar Jean-Marc'
maintainer_email 'jm.pulvar@gmail.com'
license          'All rights reserved'
description      'Installs/Configures a private WPT instance'
long_description 'Installs/Configures a private WPT instance'
version          '0.1.0'

depends 'vim', '~> 1.1.2'
depends 'apache2', '~> 2.0.0'
depends 'php', '~> 1.5.0'
depends 'php-fpm', '~> 0.6.10'
depends 'curl', '~> 2.0.0'
depends 'x264', '~> 0.5.1'
depends 'yasm', '~> 1.0.2'
depends 'ffmpeg', '~> 0.4.4'
depends 'imagemagick', '~> 0.2.3'
