name             'crd-api'
maintainer       'Pulvar Jean-Marc'
maintainer_email 'jm.pulvar@gmail.com'
license          'All rights reserved'
description      'Rest api demo for CRD project'
long_description 'Rest api demo for CRD project'
version          '0.2.1'

depends 'vim', '~>2.0.0' 
depends 'apache2', '~> 3.1.0'
depends 'composer', '~> 2.2.1'
depends 'php', '~> 1.7.2'
depends 'xdebug', '~> 1.0.0'
depends 'php-fpm', '~> 0.7.5'
depends 'phpunit', '~> 1.0.2'
depends 'phpmd', '~> 0.0.6'
depends 'phpcs', '~> 1.1.1'
depends 'curl', '~> 2.0.0'
depends 'memcached', '~> 1.7.2'
depends 'bamboo', '~> 1.6.0'
