name             'nemo-front'
maintainer       'Pulvar Jean-Marc'
maintainer_email 'jm.pulvar@gmail.com'
license          'All rights reserved'
description      'Installs/Configures nemo-front'
long_description 'Installs/Configures nemo-front'
version          '0.2.0'

depends 'vim', '~> 2.0.0'
depends 'apache2', '~> 3.2.2'
depends 'php', '~> 2.1.0'
depends 'composer', '~> 2.2.1'
depends 'php-fpm', '~> 0.7.5'
depends 'git', '~> 4.3.7'
depends 'subversion', '~> 1.3.0'
depends 'memcached', '~> 2.0.2'
depends 'curl', '~> 2.0.0'
depends 'varnish', '~> 2.5.0'
depends 'syslog-ng', '~> 0.1.0'
depends 'couchbase', '~> 1.3.2'
depends 'postgresql', '~> 4.0.6'
