name             'nemo-front'
maintainer       'Pulvar Jean-Marc'
maintainer_email 'jm.pulvar@gmail.com'
license          'All rights reserved'
description      'Installs/Configures nemo-front'
long_description 'Installs/Configures nemo-front'
version          '0.1.0'

depends 'vim', '~> 1.1.2'
depends 'apache2', '~> 2.0.0'
depends 'php-fpm', '~> 0.6.10'
depends 'git', '~> 4.0.2'
depends 'subversion', '~> 1.3.0'
depends 'memcached', '~> 1.7.2'
depends 'curl', '~> 2.0.0'
depends 'varnish', '~> 0.9.12'
